#! /bin/sh
pgrep sxhkd || sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Borders
#bspc config border_width 5px

#bspc config normal_border_color "#343b58"
#bspc config active_border_color "#34548a"
#bspc config focused_border_color "#34548a"

#Startup programs

pgrep clipster || clipster -d &

xsetroot -cursor_name left_ptr &

pgrep picom || picom --config ~/.config/bspwm/picom.conf &
~/.fehbg
#Start/Restart Polybar
~/.config/bspwm/polybar.sh &
pgrep dunst || dunst -conf ~/.config/bspwm/dunstrc &
pgrep xidlehook || xidlehook --not-when-fullscreen --not-when-audio --timer 120 'dm-tool lock' ' ' &
pgrep mpDris2 || mpDris2 &
#Rules
bspc rule -a "*:*:Picture in picture" floating=on
bspc rule -a "*:*:robloxplayerlauncher.exe" floating=on
