#! /bin/sh
sxhkd -c ~/.config/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         4
bspc config window_gap          20

bspc config focused_border_color       '#F2CDCD'
bspc config normal_border_color        '#6E6C7E'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Start/Restart Polybar
~/.config/bspwm/polybar.sh &
feh --bg-fill ~/Pictures/wallpapers/redCaboose.jpg &
dunst -conf ~/.config/bspwm/dunstrc &
xidlehook --not-when-fullscreen --not-when-audio --timer 120 i3lock-fancy ' ' &
