#!/bin/bash


# Set decoration geometry
berryc border_width       0
berryc inner_border_width 5
berryc title_height       40
berryc edge_gap           80 20 20 20

# Set decoration colors
# berryc focus_color         1E1E2E
# berryc unfocus_color       1E1E2E
berryc inner_focus_color   F2CDCD
berryc inner_unfocus_color 96CDFB
berryc text_focus_color    6E6C7E
berryc text_unfocus_color  6E6C7E

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Caskaydia Cove Nerd Font-13"
berryc json_status 			"true"
berryc decorate_new 		"true"
#berryc manage 				Dialog|Toolbar|Menu|Splash|Utility

feh --bg-fill ~/Pictures/wallpapers/shaded_landscape.png
dunst -conf ~/.config/berry/dunstrc &
polybar -r -c ~/.config/berry/polybar.ini main &
XDG_SESSION_TYPE=x11 plank
