local scheme = {}
    scheme.background    = "#0f111a"
    scheme.foreground    = "#a6accd"
    scheme.black         = "#000000"
    scheme.blue          = "#82aaff"
    scheme.brightBlack   = "#464b5d"
    scheme.brightBlue    = "#82aaff"
    scheme.brightCyan    = "#89ddff"
    scheme.brightGreen   = "#c3e88d"
    scheme.brightPurple  = "#c792ea"
    scheme.brightRed     = "#f07178"
    scheme.brightWhite   = "#ffffff"
    scheme.brightYellow  = "#ffcb6b"
    scheme.cyan          = "#89ddff"
    scheme.green         = "#c3e88d"
    scheme.purple        = "#c792ea"
    scheme.red           = "#f07178"
    scheme.white         = "#ffffff"
    scheme.yellow        = "#ffcb6b"

    return scheme