server_host = '127.0.0.1' # host address of clipcat gRPC server
server_port = 45045       # port number of clipcat gRPC server
finder = 'rofi'

[rofi]                    # options for "rofi"
line_length = 100         # length of line
menu_length = 30          # length of menu

