#!/bin/bash

#
# Autostart
#

pgrep swaybg || swaybg -m fill -i "$HOME/Pictures/wallpapers/MaterialBlueGradientStack.png" &
pgrep waybar && killall -SIGUSR2 waybar|| waybar &
pgrep mako && makoctl reload || mako &
#pgrep -f "python3 /usr/bin/mpDris2" || mpDris2 &

#
# Basic Stuff
#

riverctl map normal Super Return spawn "wezterm"
riverctl map normal Super Space spawn "wofi --show drun"
riverctl map normal Super slash spawn "neovide"
riverctl map normal Super Escape spawn "eww windows | grep -i *dashboard && eww close dashboard || eww open dashboard"

#
# Media
#

riverctl map normal None XF86AudioRaiseVolume spawn "pamixer -i 5"
riverctl map normal None XF86AudioLowerVolume spawn  "pamixer -d 5"
riverctl map normal None XF86AudioMute spawn  "pamixer -t"
riverctl map normal None XF86AudioPlay spawn  "playerctl play-pause"
riverctl map normal None XF86AudioNext spawn  "playerctl next"
riverctl map normal None XF86AudioPrev spawn  "playerctl previous"

#Screenshot
riverctl map normal None Print spawn  "$XDG_CONFIG_HOME/river/scripts/screenshot"
riverctl map normal Control Print spawn "$XDG_CONFIG_HOME/river/scripts/screenshot_select"

riverctl map normal Super semicolon spawn emote

#
# Window Managment
#

riverctl map normal Super+Shift Q exit
riverctl map normal Super+Shift R spawn "$XDG_CONFIG_HOME/river/init"
riverctl map normal Super W close

riverctl map normal Super Tab swap previous
riverctl map normal Super+Shift Tab swap next

riverctl map normal Super Left send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super Right send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super Up send-layout-cmd rivertile "main-count +1"
riverctl map normal Super Down send-layout-cmd rivertile "main-count -1"

riverctl map normal Alt Tab focus-view next
riverctl map normal Alt+Shift Tab focus-view previous

riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl map normal Super F toggle-fullscreen
riverctl map normal Super S toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done


#
# Decoration
#

riverctl set-repeat 50 300

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6

notify-send "Reloaded River Config"
