--Configuration Init
require('conf.options')
require('conf.theme')
require('conf.bindings')
require('conf.alpha')
require('conf.persistence')
require('conf.treesitter')
require('conf.nvim-tree')
require('conf.cmp')
require('conf.bufferline')
require('conf.lsp')
require('conf.feline')
require('conf.which-key')
